# Generated by Django 5.2 on 2025-06-07 11:47

from django.db import migrations
from django.contrib.auth.models import User

def migrate_user_data_to_profile(apps, schema_editor):
    """
    Migrate first_name, last_name, and email from User to UserProfile
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    for user in User.objects.all():
        # Get or create profile for this user
        profile, created = UserProfile.objects.get_or_create(user=user)
        
        # Copy data from User to UserProfile only if profile doesn't already have the data
        if not profile.first_name and user.first_name:
            profile.first_name = user.first_name
        if not profile.last_name and user.last_name:
            profile.last_name = user.last_name
        if not profile.email and user.email:
            profile.email = user.email
            
        profile.save()

def reverse_migrate_user_data(apps, schema_editor):
    """
    Reverse migration: copy data back from UserProfile to User
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        user = profile.user
        if profile.first_name:
            user.first_name = profile.first_name
        if profile.last_name:
            user.last_name = profile.last_name
        if profile.email:
            user.email = profile.email
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_user_data_to_profile, reverse_migrate_user_data),
    ]
