# Generated by Django 5.2 on 2025-06-07 11:48

from django.db import migrations


def clear_user_personal_data(apps, schema_editor):
    """
    Clear first_name, last_name, and email from User model now that they're in UserProfile
    """
    User = apps.get_model('auth', 'User')
    
    # Clear personal data from User model
    User.objects.all().update(
        first_name='',
        last_name='',
        email=''
    )

def restore_user_personal_data(apps, schema_editor):
    """
    Reverse migration: restore data from UserProfile to User
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        user = profile.user
        if profile.first_name:
            user.first_name = profile.first_name
        if profile.last_name:
            user.last_name = profile.last_name
        if profile.email:
            user.email = profile.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20250607_1847'),
    ]

    operations = [
        migrations.RunPython(clear_user_personal_data, restore_user_personal_data),
    ]
